from manim import *

VERTEX_COLOR = YELLOW_C
EDGE_COLOR = PURPLE_A

STARTING_POINT_COLOR = RED_C
ENDPOINT_COLOR = BLUE_C
PATH_COLOR = ORANGE
PATH_COLOR_TWICE = BLUE_B
SPANNING_TREE_COLOR = TEAL_C