from manim import *

ABC_COLOR = TEAL
ABC_STROKE_WIDTH = 3
ABC_Z_INDEX = 5

<<<<<<< HEAD
AD_COLOR = RED
AD_STROKE_WIDTH = 3
AD_Z_INDEX = 4

DOT_COLOR = YELLOW
DOT_STROKE_WIDTH = 2
DOT_STROKE_OPACITY = 1
DOT_FILL_OPACITY = 0.5
DOT_RADIUS = 0.15
DOT_Z_INDEX = 6

ANGLE_COLOR = PINK
ANGLE_RADIUS = 1

INNER_DOT_COLOR = GREEN
INNER_DOT_STROKE_WIDTH = 2
INNER_DOT_STROKE_OPACITY = 1
INNER_DOT_FILL_OPACITY = 0.5
INNER_DOT_RADIUS = 0.12
INNER_DOT_Z_INDEX = 7

HEIGHT_COLOR = LIGHT_BROWN
HEIGHT_STROKE_WIDTH = 2
HEIGHT_Z_INDEX = 6

ORTH_DOT_COLOR = WHITE
ORTH_DOT_STROKE_WIDTH = 2
ORTH_DOT_STROKE_OPACITY = 1
ORTH_DOT_FILL_OPACITY = 1
ORTH_DOT_RADIUS = 0.12
ORTH_DOT_Z_INDEX = 8

T_COLOR = ORANGE
T_STROKE_WIDTH = 3
T_Z_INDEX = 5

PAR_COLOR = BLUE
PAR_STROKE_WIDTH = 6
PAR_Z_INDEX = 5
=======
BISECTOR_COLOR = RED
BISECTOR_STROKE_WIDTH = 3
>>>>>>> d30123628076a7a21cb955a8c888b3a99b42b859
